# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
  #parameter_name: value

services:
  alice.processor.post:
    class: AppBundle\DataFixtures\Processor\PostProcessor
    autowire: true
    tags: [ { name: hautelook_alice.alice.processor } ]
    
  app.form.type.post:
    class: AppBundle\Form\PostFormType
    autowire: true
    tags: 
      - {name: form.type} 
      
  app.post_image_uploader:
    class: AppBundle\Service\FileUploader
    arguments:
      $targetDir: '%post_images_upload%'      
