# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
  #parameter_name: value

services:
  alice.processor.post:
    class: AppBundle\DataFixtures\Processor\PostProcessor
    autowire: true
    tags: [ { name: hautelook_alice.alice.processor } ]
